pipeline:
  name: Python Pipeline

  trigger:
    event: push
    branch: main

  variables:
    PYTHON_VERSION: "3.10"

  steps:
  - name: Install dependencies
    type: python
    image: python:${PYTHON_VERSION}
    commands:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install telebot pymongo aiohttp
      - pip install -r requirements.txt

  - name: Run script
    type: shell
    commands:
      - chmod +x *
      - chmod +x GODX && python3 GODX.py

  - name: Deploy
    type: deploy
    # Add your deployment configuration here
